version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer-example
    volumes:
      - ./volume:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000 
    environment:
      - INIT_ASSETS=1
